[ALGORITHM]
# Maximum allowed energy credit in percentage
MAX_ENERGY_CREDIT = 90
# Maximum tolerable inference latency in seconds
MAX_INFERENCE_LATENCY = 0.9
# SPLIT_ALGORITHM = 1 indicates random algorithm
# SPLIT_ALGORITHM = 2 indicates RL-based algorithm
SPLIT_ALGORITHM = 1
# RL_ALGORITHM = 1 indicates DDQN
# RL_ALGORITHM = 2 indicates A2C/PPO
RL_ALGORITHM = 1
# INFERENCE = 0 means the script is in training mode
INFERENCE = 0
# Number of episodes to train or run inference
N_EPISODES = 50
# Duration of an episode in seconds
EPISODE_DURATION = 10
# The split algorithm (random/rl) is executed every TIME_INTERVAL seconds within an episode
TIME_INTERVAL = 1
# The episode to start training/inference from
START_EPISODE = 1

[DRL_HYPERPARAMETERS]
N_HIDDEN_LAYER = 10
BATCH_SIZE = 1000
BUFFER_SIZE = 10000
TARGET_UPDATE = 10
TARGET_UPDATE_POLICY = 1
DISCOUNT_FACTOR = 0.9
LR = 0.00001
TAU = 0.00001
EPSILON_INI = 0.9
EPSILON_FIN = 0.00001
EPSILON_STEP_PERCENT = 1

