[ALGORITHM]
# Weight for the inference time
WEIGHT_INFERENCE_TIME = 0.1
# Maximum allowed energy credit in percentage
MAX_ENERGY_CREDIT = 90
# Maximum tolerable inference latency in seconds
MAX_INFERENCE_LATENCY = 2.0
# SPLIT_ALGORITHM = 1 indicates random algorithm
# SPLIT_ALGORITHM = 2 indicates RL-based algorithm
# SPLIT_ALGORITHM = 3 indicates optimal solution
# SPLIT_ALGORITHM = 4 indicates fixed split
# SPLIT_ALGORITHM = 5 indicates ue only i.e. no split
SPLIT_ALGORITHM = 2
# RL_ALGORITHM = 1 indicates DDQN
# RL_ALGORITHM = 2 indicates A2C
RL_ALGORITHM = 1
# INFERENCE = 0 means the script is in training mode
INFERENCE = 0
# Number of episodes to train or run inference
N_EPISODES = 5000
# Duration of an episode in seconds
EPISODE_DURATION = 50
# The split algorithm (random/rl) is executed every TIME_INTERVAL seconds within an episode
TIME_INTERVAL = 1
# The episode to start training/inference from
START_EPISODE = 1
# Compression rates rho
COMPRESSION_RATES = [1.0, 0.75, 0.50, 0.25]
# Top1 accuracy confidence decrease in percentage
ACCURACY_DECREASE = 80
# Accuracy weight in optimization objective
WEIGHT_ACCURACY = 0.3
# Flag to turn on/off discrete top1 accuracy confidence
TOP1_FLAG = 0
# Discrete bins for top1 accuracy confidence (i.e. low to high)
# [0.0-0.33) --> value 1, [0.33-0.66) --> value 2
# [0.66-1.0] --> value 3
TOP1_BINS = [1, 2, 3]

PARAM_PATH = 100

[DRL_HYPERPARAMETERS]
N_HIDDEN_LAYER = 10
BATCH_SIZE = 10
BUFFER_SIZE = 10000
TARGET_UPDATE = 10
TARGET_UPDATE_POLICY = 1
DISCOUNT_FACTOR = 0.9
LR = 0.00001
TAU = 0.001
EPSILON_INI = 0.9
EPSILON_FIN = 0.00001
EPSILON_STEP_PERCENT = 0.5
LR_ACTOR = 0.0001
LR_CRITIC = 0.0005
ENTROPY = 1
ENTROPY_FACTOR = 0.005
